Revert "Use tap.remote for pull_pr for Linuxbrew"
Caused pulls to fail when remote URLs ended in '.git':
```
brew pull --clean https://github.com/Homebrew/homebrew-emacs.git/pull/515
Error: Not a GitHub pull request or commit: https://github.com/Homebrew/homebrew-emacs.git/pull/515
```

This reverts commit da77eab88beb54464dbc713727caf6ac134d4be8.