tests/formulae: fix check for skipping online checks
Fixes multiple

    Error: GitHub API Error: Bad credentials
    HOMEBREW_GITHUB_API_TOKEN may be invalid or expired; check:
      https://github.com/settings/tokens

errors seen at Homebrew/homebrew-core#98809.

Formulae are removed from `@testing_formulae` after they are tested, so
we cannot use this to count the number of formulae being tested.