Set working directory on Linux
This is needed to avoid

    Error: Invalid cross-device link @ rb_file_s_link - (./testbottest--0.1.x86_64_linux.bottle.1.tar.gz, /github/home/.cache/Homebrew/downloads/9688e5b8937a63085d076f920b62cbb0139525ccca316ad61fb81e9e314a9382--testbottest--0.1.x86_64_linux.bottle.1.tar.gz)