Dockerfile: use copy instead of add
Based on dawidd6's recommendation
Fixes:
error: could not lock config file .git/config: Permission denied
Error: Command failed with exit 255: git